spring:
  application:
    name: flowable-sample
  profiles:
    active: dev
server:
  port: 8080

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zzq.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    com.zzq: debug
flowable:
  #  是否激活异步执行器
  async-executor-activate: false
  # 数据库模式更新策略，true表示自动更新数据库模式
  database-schema-update: true
